### ISSUE TITLE
What about a python 3.7 branch?

### ISSUE THREAD

**Issue by znd4** [beeware/Python-Django-template#4]
Sorry, I meant to post this earlier. Thanks @freakboy3742 and @danyeaw  for running this sprint.

Hopefully I'll see you guys in Pittsburgh!

**Comment by mulka** [comment]
I also ran into this problem with not having a 3.7 branch.

**Comment by znd4** [comment]
I would submit a PR, but I don't think it's possible to PR for a new branch.
